// src/lib/components/CategoryItem.svelte
<script>
  import BlogPreviewItem from "$lib/components/BlogPreviewItem.svelte";
  import SectionCategoryBadge from "$lib/components/SectionCategoryBadge.svelte";

  let { blogs = [], title } = $props();
</script>

{#if blogs.length > 0}
  <section class="mb-6">
    <SectionCategoryBadge {title} />
    {#each blogs as blog (blog.url || blog.title)}
      <BlogPreviewItem {blog} />
    {/each}
  </section>
{/if}

// old-site/src/pages/Writings/components/CategoryItem.jsx
import SectionCategoryBadge from "./SectionCategoryBadge";
import BlogPreviewItem from "../../../components/Home/BlogPreviewItem";

export default function CategoryItem(props) {
  const { title, blogs } = props;
  if (!blogs || blogs.length === 0) return null;
  return (
    <section className="mb-6">
      <SectionCategoryBadge title={title} />
      {blogs &&
        blogs.map((blog) => <BlogPreviewItem key={blog.slug} blog={blog} />)}
    </section>
  );
}
