// src/lib/components/ProjectButtonRed.svelte
<script>
  let { url } = $props();
</script>

<a
  class="mr-2 flex items-center rounded-full bg-red-500 px-2 py-1.5 text-xs text-white"
  href={url}
  rel="noreferrer"
  target="_blank"
>
  <img src="/assets/icons/icon-code.png" alt="" class="mr-2 block h-[15px] w-[15px]" />
  <span>View code</span>
</a>

// src/pages/Projects/components/ProjectButtonRed.jsx
import codeButton from "../../../../src/assets/icons/icon-code.png";


export default function ProjectButtonRed(props) {
  const { url } = props;

  return (
    <a
      className="flex items-center text-xs bg-red-500 text-white px-2 py-1.5 rounded-full mr-2"
      href={url}
      rel="noreferrer"
      target="_blank"
    >
      <img src={codeButton} alt="" className="block w-[15px] h-[15px] mr-2" />
      <span>View code</span>
    </a>
  );
}
