// src/lib/components/ProjectsPage.svelte
<script>
  import ProjectItem from "$lib/components/ProjectItem.svelte";
  import { ALL_PROJECTS } from "$lib/data/projects/allProjects.js";

  const visibleProjects = ALL_PROJECTS.filter((project) => !project.hidden);
</script>

<section class="mb-8 mt-10">
  {#each visibleProjects as project (project.title)}
    <ProjectItem {project} />
  {/each}
</section>

// src/pages/Projects/ProjectsPage.jsx
import React from "react";
import { ALL_PROJECTS } from "./allProjects";
import RootLayout from "../../components/RootLayout";
import ProjectItem from "./components/ProjectItem";


export default function ProjectsPage(props) {

  console.log("-- projects: ", ALL_PROJECTS)

  return (
    <RootLayout>
      <section className="mt-10 mb-8">
        {ALL_PROJECTS.map(projectItem => (
          <ProjectItem project={projectItem} />
        ))}
      </section>
    </RootLayout>
  );
}
