// src/components/Home/BlogPreviewItem.jsx
import React from "react";

export default function BlogPreviewItem(props) {
  const { blog } = props;

  return (
    <a
      href={blog.url}
      rel="noreferrer"
      target="_blank"
      className="block mb-1 border-l-2 border-black pl-2 my-2 hover:underline hover:border-yellow-500 transition duration-300 ease-in-out"
    >
      <h2 className="text-xs">{blog.title}</h2>
    </a>
  );
}

// src/lib/components/BlogPreviewItem.svelte
<script>
  let { blog } = $props();
</script>

<a
  href={blog.url}
  rel="noreferrer"
  target="_blank"
  class="my-2 mb-1 block border-l-2 border-black pl-2 transition duration-300 ease-in-out hover:border-yellow-500 hover:underline"
>
  <h2 class="text-[15px] text-gray-900">{blog.title}</h2>
</a>
