// src/components/MainNav.jsx
import React from "react";
import { Link } from "react-router-dom";
import { ArrowTopRightOnSquareIcon } from "@heroicons/react/24/outline";

export const RESUME_URL =
  "https://drive.google.com/file/d/1qvwCcXTBK9MLgm9YCQZn6fPuRbfKww4v/view?usp=sharing";

export default function MainNav() {
  return (
    <section>
      <nav className="fixed top-0 left-0 z-40 md:h-[65px] bg-white text-gray-900 w-full border-b border-b-gray-200 py-4 md:py-0">
        <div
          className={`px-2 md:min-w-[600px] max-w-[750px] mx-auto flex flex-col md:flex-row justify-between items-center md:h-[65px]`}
        >
          <Link
            to="/"
            className="flex items-center font-libreBaskerville text-2xl"
          >
            <span className="ml-3">Eduardo Garza</span>
          </Link>
          <div className="flex pt-4 md:pt-0">
            <Link to="/projects" className="hover:underline text-sm ml-6">
              Projects
            </Link>
            <a
              href={RESUME_URL}
              target="_blank"
              rel="noreferrer"
              className="hover:underline text-sm ml-6 flex items-center"
            >
              <span className="mr-2">Resume</span>
              <ArrowTopRightOnSquareIcon className="w-4 h-4 block text-gray-800" />
            </a>
          </div>
        </div>
      </nav>
      <section className="pt-[115px] md:pt-[65px]"></section>
    </section>
  );
}

// src/lib/components/MainNav.svelte
<script>
  import { page } from "$app/state";
  import { RESUME_URL } from "$lib/data/links.js";

  const isCurrentPath = (path) => page.url.pathname === path;
</script>

<section>
  <nav class="fixed left-0 top-0 z-40 w-full border-b border-b-gray-200 bg-white py-4 text-gray-900 md:h-[65px] md:py-0">
    <div class="mx-auto flex max-w-[750px] flex-col items-center justify-between px-2 md:h-[65px] md:min-w-[600px] md:flex-row">
      <a class="flex items-center font-libreBaskerville text-2xl" href="/">
        <span class="ml-3">Eduardo Garza</span>
      </a>
      <div class="flex pt-4 md:pt-0">
        <a
          class="ml-6 text-sm hover:underline"
          aria-current={isCurrentPath("/projects") ? "page" : undefined}
          href="/projects"
        >
          Projects
        </a>
        <a
          class="ml-6 flex items-center text-sm hover:underline"
          href={RESUME_URL}
          rel="noreferrer"
          target="_blank"
        >
          <span class="mr-2">Resume</span>
          <svg
            aria-hidden="true"
            class="block h-4 w-4 text-gray-800"
            data-slot="icon"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </a>
      </div>
    </div>
  </nav>
  <section class="pt-[115px] md:pt-[65px]"></section>
</section>
