// src/pages/Projects/components/ProjectButtonBlue.jsx
import playButton from "../../../../src/assets/icons/icon-play.png";

export default function ProjectButtonBlue(props) {
  const { url } = props;

  return (
    <a
      className="flex items-center text-xs bg-blue-600 text-white px-2 py-1.5 rounded-full mr-2"
      href={url}
      rel="noreferrer"
      target="_blank"
    >
      <img src={playButton} alt="" className="block w-[15px] h-[15px] mr-2" />
      <span>Try demo</span>
    </a>
  );
}

// src/lib/components/ProjectButtonBlue.svelte
<script>
  let { url } = $props();
</script>

<a
  class="mr-2 flex items-center rounded-full bg-blue-600 px-2 py-1.5 text-xs text-white"
  href={url}
  rel="noreferrer"
  target="_blank"
>
  <img src="/assets/icons/icon-play.png" alt="" class="mr-2 block h-[15px] w-[15px]" />
  <span>Try demo</span>
</a>
