// src/pages/Projects/components/ProjectItem.jsx
import React from "react";
import { Link } from "react-router-dom";
import ProjectButtonRed from "./ProjectButtonRed";
import ProjectButtonBlue from "./ProjectButtonBlue";

export default function ProjectItem(props) {
  const { project } = props;
  if (!project) return null;

  const {
    title,
    description,
    bulletPoints = [],
    bulletPointSections = [],
    imagePath,
    tools,
    extendedDescription,
    detailsURL,
    detailsLabel = "View archive",
    previewImagePaths = [],
    repositoryURL,
    demoURL,
    videoURLs = [],
  } = project;

  if (!title) return null;

  return (
    <section className="mb-10">
      <section className="border border-gray-200 p-6 rounded-2xl shadow-sm">
        <section className="flex flex-col md:flex-row">
          {imagePath && (
            <section className="flex items-center justify-center md:items-start md:py-4">
              <img
                src={imagePath}
                alt={title}
                className="block w-[50px] rounded-full"
              />
            </section>
          )}
          <section className="ml-6 flex-1">
            <header className="mb-2 text-center md:text-left">
              <h2 className="font-medium text-[20px] text-medium">{title}</h2>
              <p className="text-sm text-gray-500 text-[14px]">{description}</p>
            </header>
            <section className="flex flex-wrap mb-2 justify-center md:justify-start">
              {tools &&
                tools.map((toolName) => (
                  <p
                    className="text-xs mr-1 mb-2 bg-gray-200 rounded-full py-1 px-2 text-gray-700 hover:bg-gray-300 cursor-pointer transition duration-500 ease-in-out"
                    key={toolName}
                  >
                    {toolName}
                  </p>
                ))}
            </section>
            <section className="flex justify-center items-center md:justify-stretch">
              {detailsURL && (
                <Link
                  className="mr-2 inline-flex items-center rounded-full bg-gray-900 px-3 py-2 text-xs text-white transition duration-200 hover:bg-gray-700"
                  to={detailsURL}
                >
                  <span>{detailsLabel}</span>
                </Link>
              )}
              {repositoryURL && <ProjectButtonRed url={repositoryURL} />}
              {demoURL && <ProjectButtonBlue url={demoURL} />}
            </section>
            {detailsURL && previewImagePaths.length > 0 && (
              <Link
                className="mt-4 flex flex-wrap justify-center gap-2 md:justify-start"
                to={detailsURL}
              >
                {previewImagePaths.map((previewImagePath, index) => (
                  <img
                    alt={`${title} preview ${index + 1}`}
                    className="h-14 w-14 rounded-xl object-cover shadow-sm transition duration-200 hover:scale-[1.03]"
                    key={previewImagePath}
                    src={previewImagePath}
                  />
                ))}
              </Link>
            )}
          </section>
        </section>
        <section className="mt-4 text-center md:text-left">
          <p className="text-gray-900 leading-[200%] text-[14.5px]">
            {extendedDescription}
          </p>
          {bulletPoints.length > 0 && (
            <ul className="mt-2 list-inside list-disc text-[14.5px] leading-[200%] text-gray-900">
              {bulletPoints.map((bulletPoint) => (
                <li key={bulletPoint}>{bulletPoint}</li>
              ))}
            </ul>
          )}
          {bulletPointSections.length > 0 && (
            <section className="mt-3 space-y-3">
              {bulletPointSections.map((bulletPointSection) => (
                <section key={bulletPointSection.title}>
                  <h3 className="mb-1 text-[10px] font-semibold uppercase tracking-wider text-gray-900">
                    {bulletPointSection.title}
                  </h3>
                  <ul className="list-inside list-disc text-[14.5px] leading-[200%] text-gray-900">
                    {bulletPointSection.items.map((bulletPoint) => (
                      <li key={bulletPoint}>{bulletPoint}</li>
                    ))}
                  </ul>
                </section>
              ))}
            </section>
          )}
        </section>
      </section>
      {videoURLs.length > 0 &&
        videoURLs.map((videoURL, index) => (
          <section
            className="flex items-center justify-center mt-10"
            key={index}
          >
            <iframe
              allowFullScreen
              src={videoURL}
              title={title}
              className="w-[450px] h-[300px] rounded-2xl"
            ></iframe>
          </section>
        ))}
    </section>
  );
}

// src/lib/components/ProjectItem.svelte
<script>
  import HighlightedText from "$lib/components/HighlightedText.svelte";
  import ProjectBulletList from "$lib/components/ProjectBulletList.svelte";
  import ProjectButtonBlue from "$lib/components/ProjectButtonBlue.svelte";
  import ProjectButtonRed from "$lib/components/ProjectButtonRed.svelte";

  let { project } = $props();
</script>

{#if project?.title}
  <section class="mb-10">
    <section class="rounded-2xl border border-gray-200 p-6 shadow-sm">
      <section class="flex flex-col md:flex-row">
        {#if project.imagePath}
          <section class="flex items-center justify-center md:items-start md:py-4">
            <img src={project.imagePath} alt={project.title} class="block w-[50px] rounded-full" />
          </section>
        {/if}

        <section class="ml-6 flex-1">
          <header class="mb-2 text-center md:text-left">
            <h2 class="text-medium text-[20px] font-medium">{project.title}</h2>
            <p class="text-[14px] text-sm text-gray-500">{project.description}</p>
          </header>

          {#if project.tools}
            <section class="mb-2 flex flex-wrap justify-center md:justify-start">
              {#each project.tools as toolName (toolName)}
                <p
                  class="mb-2 mr-1 cursor-pointer rounded-full border border-gray-200 bg-white px-2 py-1 text-xs text-gray-700 transition duration-500 ease-in-out hover:bg-gray-50"
                >
                  {toolName}
                </p>
              {/each}
            </section>
          {/if}

          <section class="flex items-center justify-center md:justify-stretch">
            {#if project.detailsURL}
              <a
                class="mr-2 inline-flex items-center rounded-full bg-gray-900 px-3 py-2 text-xs text-white transition duration-200 hover:bg-gray-700"
                href={project.detailsURL}
              >
                <span>{project.detailsLabel || "View archive"}</span>
              </a>
            {/if}
            {#if project.repositoryURL}
              <ProjectButtonRed url={project.repositoryURL} />
            {/if}
            {#if project.demoURL}
              <ProjectButtonBlue url={project.demoURL} />
            {/if}
          </section>

          {#if project.detailsURL && project.previewImagePaths?.length > 0}
            <a class="mt-4 flex flex-wrap justify-center gap-2 md:justify-start" href={project.detailsURL}>
              {#each project.previewImagePaths as previewImagePath, index (previewImagePath)}
                <img
                  alt={`${project.title} preview ${index + 1}`}
                  class="h-14 w-14 rounded-xl object-cover shadow-sm transition duration-200 hover:scale-[1.03]"
                  src={previewImagePath}
                />
              {/each}
            </a>
          {/if}
        </section>
      </section>

      <section class="mt-4 text-center md:text-left">
        <p class="text-[14.5px] leading-[200%] text-gray-900">
          <HighlightedText text={project.extendedDescription} highlightTerms={project.highlightTerms || []} />
        </p>

        <ProjectBulletList
          bulletPoints={project.bulletPoints || []}
          highlightTerms={project.highlightTerms || []}
        />

        {#if project.bulletPointSections?.length}
          <section class="mt-3 space-y-3">
            {#each project.bulletPointSections as bulletPointSection (bulletPointSection.title)}
              <section>
                <h3 class="mb-1 text-[11px] font-semibold uppercase text-gray-400">
                  {bulletPointSection.title}
                </h3>
                <ProjectBulletList
                  bulletPoints={bulletPointSection.items}
                  className=""
                  highlightTerms={project.highlightTerms || []}
                />
              </section>
            {/each}
          </section>
        {/if}
      </section>
    </section>

    {#if project.videoURLs?.length > 0}
      {#each project.videoURLs as videoURL, index (videoURL)}
        <section class="mt-10 flex items-center justify-center">
          <iframe
            allowfullscreen
            src={videoURL}
            title={`${project.title} ${index + 1}`}
            class="h-[300px] w-[450px] rounded-2xl"
          ></iframe>
        </section>
      {/each}
    {/if}
  </section>
{/if}
